server {
    listen 80;

    location /pedidos {
        proxy_pass http://pedidos:5001/pedidos;
    }

    location /estoque {
        proxy_pass http://estoque:5002/estoque;
    }

    location /pagamentos {
        proxy_pass http://pagamentos:5003/pagamentos;
    }
}